# Generated by Django 3.1.7 on 2021-03-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Verification email will be sent to this email.', max_length=50, unique=True, verbose_name='Email')),
                ('username', models.CharField(help_text='This will be used to identify you profile.', max_length=15, unique=True, verbose_name='Username')),
                ('mob_number', models.IntegerField(help_text='Verification code will be sent on this number.', unique=True, verbose_name='Mobile Number')),
                ('password', models.CharField(help_text="<ul class='errorlist text-muted'><li>Your password can 't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can 't be a commonly used password.</li> <li>Your password can 't be entirely numeric.<li></ul>", max_length=25, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'UserRegister',
                'verbose_name_plural': 'UserRegisters',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
