# Generated by Django 3.1.7 on 2021-03-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20210316_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(help_text="<ul>             <li>Your password can 't be too similar to your other personal information.</li>             <li>Your password must contain at least 8 characters.</li>             <li>Your password can 't be a commonly used password.</li>             <li>Your password can 't be entirely numeric.</li>             </ul>", max_length=25, verbose_name='Password'),
        ),
    ]
