# Generated by Django 3.1.7 on 2021-03-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20210316_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregister',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
